import Anthropic from '@anthropic-ai/sdk';
import { callTool, isServerAvailable } from '../../utils/mcp-client-manager.js';
import type { SocialMention, MentionIntent } from '../../types.js';

// Classification uses Haiku (fast, cheap) — matches classifier.ts pattern
const CLASSIFICATION_MODEL = 'claude-haiku-4-5-20251001';
// Reply generation uses Sonnet (quality) — matches agent.ts pattern
const GENERATION_MODEL = 'claude-sonnet-4-20250514';

const AI_SKEPTICISM_KEYWORDS = [
  'trust ai', 'just an algorithm', 'chatgpt', 'bot', 'ai-generated',
  'ai generated', 'real doctor', 'actually know', 'generated by',
];

let anthropicClient: Anthropic | null = null;
function getClient(): Anthropic {
  if (!anthropicClient) anthropicClient = new Anthropic();
  return anthropicClient;
}

// ── Classification ───────────────────────────────────────────────────

interface MentionClassification {
  intent: MentionIntent;
  confidence: number;
  reasoning: string;
}

const CLASSIFICATION_TOOL = {
  name: 'classify_mention_intent',
  description: 'Classify the intent of a social media reply directed at OrthoTriage Master (OTM).',
  input_schema: {
    type: 'object' as const,
    properties: {
      intent: {
        type: 'string',
        enum: ['CORRECTION', 'CLINICAL_QUESTION', 'ENGAGEMENT', 'PUSHBACK', 'SOURCING', 'IGNORE'],
        description: 'The intent category.',
      },
      confidence: {
        type: 'number',
        description: 'Confidence in the classification, 0 to 1.',
      },
      reasoning: {
        type: 'string',
        description: 'Brief reasoning for the classification.',
      },
    },
    required: ['intent', 'confidence', 'reasoning'],
  },
};

const CLASSIFICATION_SYSTEM_PROMPT = `You are classifying the intent of a social media reply directed at OrthoTriage Master (OTM), an AI sports injury analysis platform founded by a board-certified orthopedic surgeon.

Classify into exactly one category:

- CORRECTION: User is disputing a specific factual claim (wrong player, wrong team, wrong injury type, wrong timeline). Must reference a specific claim.
- CLINICAL_QUESTION: User is asking a genuine medical or recovery question about an injury, timeline, or rehabilitation.
- ENGAGEMENT: User is reacting positively, sharing enthusiasm, or adding color commentary. Not a question or dispute.
- PUSHBACK: User disagrees with OTM's clinical estimate but provides no factual basis — just opinion or fan sentiment.
- SOURCING: User is asking for the basis, source, or provenance of OTM's analysis ("where did you get this?", "source?").
- IGNORE: Trolling, spam, bots, hostile without substance, completely off-topic, or unintelligible.

Be strict about CORRECTION vs PUSHBACK: CORRECTION requires a specific factual claim being disputed. "This is wrong" without specifics is PUSHBACK, not CORRECTION.`;

export async function classifyMention(mention: SocialMention): Promise<MentionClassification> {
  const anthropic = getClient();

  const userMessage = `Classify this social media mention directed at OrthoTriage Master (OTM):

Platform: ${mention.platform}
Message: "${mention.text}"
Author: @${mention.authorHandle}`;

  try {
    const response = await anthropic.messages.create({
      model: CLASSIFICATION_MODEL,
      max_tokens: 256,
      system: CLASSIFICATION_SYSTEM_PROMPT,
      tools: [CLASSIFICATION_TOOL],
      tool_choice: { type: 'tool', name: 'classify_mention_intent' },
      messages: [{ role: 'user', content: userMessage }],
    });

    const toolUse = response.content.find((b) => b.type === 'tool_use');
    if (!toolUse || toolUse.type !== 'tool_use') {
      throw new Error('Classifier did not return a tool_use block');
    }

    const input = toolUse.input as Record<string, unknown>;
    return {
      intent: input.intent as MentionIntent,
      confidence: Number(input.confidence ?? 0),
      reasoning: String(input.reasoning ?? ''),
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[ReplyAgent] Classification failed for mention ${mention.mentionId}: ${message}`);
    // Default to IGNORE on failure to prevent bad replies
    return { intent: 'IGNORE', confidence: 0, reasoning: 'Classification failed' };
  }
}

// ── Reply Generation ─────────────────────────────────────────────────

interface ReplyGenerationResult {
  replyText: string;
  correctionData?: {
    field: string;
    oldValue: string;
    newValue: string;
  };
}

function detectAiSkepticism(text: string): boolean {
  const lower = text.toLowerCase();
  return AI_SKEPTICISM_KEYWORDS.some((kw) => lower.includes(kw));
}

function getCharLimit(platform: SocialMention['platform']): number {
  return platform === 'twitter' ? 240 : 320;
}

function buildSystemPrompt(mention: SocialMention, intent: MentionIntent, aiSkepticism: boolean): string {
  const charLimit = getCharLimit(mention.platform);
  const signature = '— OrthoTriage Master | AI-generated analysis. Physician-founded.';

  const base = `You are OrthoTriage Master (OTM), an AI sports injury analysis platform founded by a board-certified orthopedic surgeon. Your voice is confident, clinical, and direct — like a cool ESPN sportscaster with orthopedic authority. Never apologetic. Never sycophantic. Sign your reply with: ${signature}

Platform: ${mention.platform === 'twitter' ? 'X/Twitter' : 'Farcaster'}
Character limit: ${charLimit} characters (including signature).`;

  switch (intent) {
    case 'CORRECTION':
      return `${base}

A user has corrected a factual claim in OTM's analysis. Acknowledge the correction directly and graciously. State the correct information using clinical language. Do not be defensive. If the correction involves player team, injury classification, or RTP timeline, note the analysis will be updated.

Also extract the correction into JSON at the end of your thinking, but keep it out of the reply text. Return the reply text only.`;

    case 'CLINICAL_QUESTION':
      return `${base}

A user has asked a genuine medical or recovery question. Answer within OTM's clinical scope: tissue biology, healing timelines, RTP methodology, sport-specific load considerations. Be specific and grounded. Note this is AI-generated analysis reviewed by a physician. Keep under ${charLimit} characters.`;

    case 'ENGAGEMENT':
      if (aiSkepticism) {
        return `${base}

A user expressed skepticism about trusting AI-generated analysis. Do NOT be defensive. Lead with physician-founded framing FIRST, then the clinical grounding. Structure: [Human oversight statement] → [Clinical basis for the specific claim]. Confidence comes from the evidence, not from asserting credibility. Under ${charLimit} characters.`;
      }
      return `${base}

A user is engaging positively with OTM's analysis. Respond briefly — confident, clinical, no fluff. Add one clinical data point that extends the conversation. Do not just say "thanks." Make the reply worth reading. Under 200 characters.`;

    case 'PUSHBACK':
      return `${base}

A user disagrees with OTM's clinical estimate without providing factual basis. Hold the position. Do not capitulate, do not escalate. Restate the clinical evidence briefly. The biology of healing does not change based on fan sentiment. Tone: confident, not combative. Under ${charLimit} characters.`;

    case 'SOURCING':
      return `${base}

A user is asking for the basis of OTM's analysis. Explain the methodology briefly: injury report data, practice participation signals, sport-specific clinical literature, physician review. Note physician-founded status. This is the single most important funnel to the web frontend — always reference that a full breakdown is available. Under ${charLimit} characters.`;

    default:
      return base;
  }
}

const CORRECTION_EXTRACTION_TOOL = {
  name: 'extract_correction_data',
  description: 'Generate the reply text and extract structured correction data from a CORRECTION-intent mention.',
  input_schema: {
    type: 'object' as const,
    properties: {
      reply_text: {
        type: 'string',
        description: 'The reply to post publicly.',
      },
      correction_field: {
        type: 'string',
        description: "The field being corrected (e.g. 'player_team', 'injury_type', 'rtp_weeks').",
      },
      old_value: {
        type: 'string',
        description: "What OTM originally stated.",
      },
      new_value: {
        type: 'string',
        description: "The corrected value from the user.",
      },
    },
    required: ['reply_text', 'correction_field', 'old_value', 'new_value'],
  },
};

const REPLY_TOOL = {
  name: 'generate_reply',
  description: 'Generate the reply text to post publicly.',
  input_schema: {
    type: 'object' as const,
    properties: {
      reply_text: {
        type: 'string',
        description: 'The reply to post publicly.',
      },
    },
    required: ['reply_text'],
  },
};

export async function generateReply(
  mention: SocialMention,
  intent: MentionIntent,
): Promise<ReplyGenerationResult> {
  const anthropic = getClient();
  const aiSkepticism = intent === 'ENGAGEMENT' && detectAiSkepticism(mention.text);
  const systemPrompt = buildSystemPrompt(mention, intent, aiSkepticism);
  const useCorrectionTool = intent === 'CORRECTION';

  const userMessage = `Generate a reply to this ${mention.platform} mention:

"${mention.text}"

— @${mention.authorHandle}`;

  try {
    const tool = useCorrectionTool ? CORRECTION_EXTRACTION_TOOL : REPLY_TOOL;

    const response = await anthropic.messages.create({
      model: GENERATION_MODEL,
      max_tokens: 512,
      system: systemPrompt,
      tools: [tool],
      tool_choice: { type: 'tool', name: tool.name },
      messages: [{ role: 'user', content: userMessage }],
    });

    const toolUse = response.content.find((b) => b.type === 'tool_use');
    if (!toolUse || toolUse.type !== 'tool_use') {
      throw new Error('Reply generator did not return a tool_use block');
    }

    const input = toolUse.input as Record<string, unknown>;

    if (useCorrectionTool) {
      return {
        replyText: String(input.reply_text ?? ''),
        correctionData: {
          field: String(input.correction_field ?? 'unknown'),
          oldValue: String(input.old_value ?? ''),
          newValue: String(input.new_value ?? ''),
        },
      };
    }

    return { replyText: String(input.reply_text ?? '') };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[ReplyAgent] Reply generation failed for mention ${mention.mentionId}: ${message}`);
    throw err;
  }
}

// ── Publish ──────────────────────────────────────────────────────────

interface PublishReplyResult {
  replyId: string;
}

async function publishReply(mention: SocialMention, replyText: string): Promise<PublishReplyResult> {
  if (mention.platform === 'twitter') {
    const raw = await callTool('twitter', 'twitter_publish_tweet', {
      text: replyText,
      reply_to_id: mention.mentionId,
    });
    const parsed = JSON.parse((raw as { content: Array<{ text: string }> }).content[0].text) as { id: string };
    return { replyId: parsed.id };
  } else {
    const raw = await callTool('farcaster', 'farcaster_publish_cast', {
      text: replyText,
      parent_cast_hash: mention.mentionId,
    });
    const parsed = JSON.parse((raw as { content: Array<{ text: string }> }).content[0].text) as { hash: string };
    return { replyId: parsed.hash };
  }
}

// ── Orchestrator ─────────────────────────────────────────────────────

export interface MentionProcessResult {
  mentionId: string;
  platform: SocialMention['platform'];
  intent: MentionIntent;
  action: 'replied' | 'queued_correction' | 'ignored';
  replyText?: string;
  replyId?: string;
}

export async function processMention(mention: SocialMention): Promise<MentionProcessResult> {
  const isDryRun = process.env.SOCIAL_MONITOR_DRY_RUN === 'true';

  // Step 1: Classify intent
  const classification = await classifyMention(mention);
  const { intent, confidence } = classification;

  console.log(
    `[ReplyAgent] @${mention.authorHandle} on ${mention.platform}: ${intent} (confidence=${confidence.toFixed(2)}) — "${mention.text.slice(0, 60)}..."`
  );

  // Step 2: IGNORE — log and exit
  if (intent === 'IGNORE') {
    await logProcessedMention(mention, intent, confidence, 'IGNORED', null, null);
    return { mentionId: mention.mentionId, platform: mention.platform, intent, action: 'ignored' };
  }

  // Step 3: Generate reply
  let replyText: string;
  let correctionData: ReplyGenerationResult['correctionData'];

  try {
    const generated = await generateReply(mention, intent);
    replyText = generated.replyText;
    correctionData = generated.correctionData;
  } catch {
    // Generation failed — log as IGNORED to avoid reprocessing loop
    await logProcessedMention(mention, intent, confidence, 'IGNORED', null, null);
    return { mentionId: mention.mentionId, platform: mention.platform, intent, action: 'ignored' };
  }

  // Step 4: CORRECTION with high confidence → queue for admin review
  if (intent === 'CORRECTION' && confidence > 0.8 && correctionData) {
    // Try to find the original OTM post being corrected
    let originalPostId: string | undefined;
    if (mention.parentPostId && isServerAvailable('web')) {
      try {
        const raw = await callTool('web', 'web_list_posts', {});
        // parentPostId in this context is the tweet/cast ID of OTM's post,
        // not the DB UUID. We log it as-is; admin can cross-reference.
        originalPostId = undefined; // Cannot reliably resolve tweet ID → DB UUID without additional tooling
        void raw; // suppress unused warning
      } catch {
        // Non-fatal
      }
    }

    if (isServerAvailable('web')) {
      try {
        await callTool('web', 'web_insert_pending_correction', {
          ...(originalPostId ? { original_post_id: originalPostId } : {}),
          mention_id: mention.mentionId,
          platform: mention.platform,
          correction_field: correctionData.field,
          old_value: correctionData.oldValue,
          new_value: correctionData.newValue,
          submitted_by_handle: mention.authorHandle,
        });
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.warn(`[ReplyAgent] Failed to queue correction: ${message}`);
      }
    }

    // Still post the gracious acknowledgment reply
    let replyId: string | undefined;
    if (!isDryRun) {
      try {
        const result = await publishReply(mention, replyText);
        replyId = result.replyId;
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.warn(`[ReplyAgent] Failed to publish correction reply: ${message}`);
      }
    } else {
      console.log(`[ReplyAgent] [DRY RUN] Would reply to @${mention.authorHandle}: "${replyText}"`);
    }

    await logProcessedMention(mention, intent, confidence, 'QUEUED_CORRECTION', replyText, replyId ?? null);
    return { mentionId: mention.mentionId, platform: mention.platform, intent, action: 'queued_correction', replyText, replyId };
  }

  // Step 5: All other non-IGNORE intents → publish reply
  let replyId: string | undefined;
  if (!isDryRun) {
    try {
      const result = await publishReply(mention, replyText);
      replyId = result.replyId;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`[ReplyAgent] Failed to publish reply to @${mention.authorHandle}: ${message}`);
      await logProcessedMention(mention, intent, confidence, 'IGNORED', replyText, null);
      return { mentionId: mention.mentionId, platform: mention.platform, intent, action: 'ignored' };
    }
  } else {
    console.log(`[ReplyAgent] [DRY RUN] Would reply to @${mention.authorHandle} (${intent}): "${replyText}"`);
  }

  await logProcessedMention(mention, intent, confidence, 'REPLIED', replyText, replyId ?? null);
  return { mentionId: mention.mentionId, platform: mention.platform, intent, action: 'replied', replyText, replyId };
}

// ── DB Logging ───────────────────────────────────────────────────────

async function logProcessedMention(
  mention: SocialMention,
  intent: MentionIntent,
  confidence: number,
  actionTaken: string,
  replyContent: string | null,
  replyPostId: string | null,
): Promise<void> {
  if (!isServerAvailable('web')) return;

  try {
    await callTool('web', 'web_insert_processed_mention', {
      platform: mention.platform,
      mention_id: mention.mentionId,
      author_handle: mention.authorHandle,
      ...(mention.authorFollowerCount !== undefined ? { author_follower_count: mention.authorFollowerCount } : {}),
      mention_text: mention.text,
      intent,
      intent_confidence: confidence,
      action_taken: actionTaken,
      ...(replyContent ? { reply_content: replyContent } : {}),
      ...(replyPostId ? { reply_post_id: replyPostId } : {}),
      raw_payload: mention.rawPayload,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`[ReplyAgent] Failed to log processed mention ${mention.mentionId}: ${message}`);
  }
}
